title: Shahed poems
description: This site contains Shahed poems
theme: just-the-docs

url: https://shahed-poems.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
